import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { SocketProvider } from "@/providers/socket-provider";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import Template from "./template";
import StoreProvider from "@/providers/storeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>
          <Header />
          <Sidebar />
          <StoreProvider>
            <Template>{children}</Template>
          </StoreProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
